const data = {
  products: [
    {
      name: 'product1 tool',
      slug: 'product1-tool',
      image: '/images/p1.png',
      price: 230,
      countInTock: 10,
      brand: 'company1',
      rating: 3.4,
      numReviews: 10,
      decription: 'good',
    },
    {
      name: 'product2 tool',
      slug: 'product2-tool',
      image: '/images/p2.png',
      price: 230,
      countInTock: 10,
      brand: 'company2',
      rating: 3.4,
      numReviews: 10,
      decription: 'good',
    },
    {
      name: 'product3 tool',
      slug: 'product3-tool',
      image: '/images/p3.png',
      price: 230,
      countInTock: 10,
      brand: 'company3',
      rating: 3.4,
      numReviews: 10,
      decription: 'good',
    },
    {
      name: 'product4 tool',
      slug: 'product4-tool',
      image: '/images/p4.png',
      price: 230,
      countInTock: 10,
      brand: 'company4',
      rating: 3.4,
      numReviews: 10,
      decription: 'good',
    },
  ],
};
export default data;
